# Generated by Django 4.2.7 on 2023-11-26 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=4, max_digits=4)),
                ('description', models.TextField()),
                ('image1', models.ImageField(upload_to='uploads/products')),
                ('image2', models.ImageField(upload_to='uploads/products')),
                ('image3', models.ImageField(upload_to='uploads/products')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smarttech.category')),
            ],
        ),
    ]
